[package]
name = "concerto-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-cron-scheduler = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
linkme = { workspace = true }
tracing = { workspace = true }