app:
  # Task execution interval (using shorthand format with suffix)
  interval: "7s"
  
  # Timezone for cron jobs
  zone: "Asia/Jakarta"
  
  # Enable/disable conditional task
  task_enabled: true
  
  # Custom cron expression
  cron_expression: "0 */3 * * * *"
  
  # Report settings (interval value only, time_unit is compile-time constant)
  report:
    interval: 30
  
  # Notification settings
  notifications:
    enabled: true
    email: "admin@example.com"

database:
  host: "localhost"
  port: 5432
  name: "myapp_db"

features:
  email_notifications: true
  sms_alerts: false
  logging_level: "info"
