[app]
# Task execution interval (default unit is milliseconds)
interval = 5000

# Timezone for cron jobs (e.g., "Asia/Jakarta", "UTC", "local")
zone = "Asia/Jakarta"

# Enable/disable conditional task
task_enabled = true

# Custom cron expression
cron_expression = "0 */2 * * * *"

# Task with seconds (using shorthand suffix)
fast_interval = "3s"

# Task with minutes (number only, time_unit specified in code)
backup_interval = 2

[database]
host = "localhost"
port = 5432

[features]
email_notifications = true
