[package]
name = "runnable-example"
version = "0.1.0"
edition = "2021"

[dependencies]
scheduled = { path = "../../scheduled" }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"

[[bin]]
name = "runnable-example"
path = "src/main.rs"
